FROM nginx:stable
MAINTAINER stanley@linuxsimba.com

RUN apt-get -yq update
RUN apt-get -yq install git
RUN git clone https://github.com/linuxsimba/security_monkey /usr/local/src/security_monkey

WORKDIR /usr/local/src/security_monkey

RUN git checkout tags/v0.7.4 -b v0.7.4

COPY nginx.conf /etc/nginx/nginx.conf

COPY create_ssl_key.sh /tmp/create_ssl_key.sh

EXPOSE 443

RUN bash /tmp/create_ssl_key.sh

ADD static.tar /usr/local/src/security_monkey/security_monkey
