version: '2'

networks:
  securitymonkey_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.202.0/24
          gateway: 192.168.202.1

services:
  postgres:
    image: postgres:9.6
    container_name: postgres
    environment:
      POSTGRES_USER: securitymonkeyuser
      POSTGRES_PASSWORD: securitymonkeypass
      POSTGRES_DB: securitymonkeydb
    networks:
      - securitymonkey_net
  securitymonkey:
    build:
      context: .
      dockerfile: Dockerfile.securitymonkey_noaws
    image: linuxsimba/securitymonkey
    networks:
      securitymonkey_net:
        ipv4_address: 192.168.202.3
    container_name: securitymonkey
    depends_on:
      - postgres
    ports:
      - "443:443"
