version: '2'

networks:
  securitymonkey_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.202.0/24
          gateway: 192.168.202.1

services:
  postgres:
    image: postgres:9.6
    container_name: postgres
    environment:
      POSTGRES_USER: securitymonkeyuser
      POSTGRES_PASSWORD: securitymonkeypass
      POSTGRES_DB: securitymonkeydb
    networks:
      - securitymonkey_net
  securitymonkey:
    build: .
    image: linuxsimba/securitymonkey
    networks:
      - securitymonkey_net
    container_name: securitymonkey
    depends_on:
      - postgres
